apiVersion: v1
kind: Service
metadata:
  labels:
    app: orion
  name: orion
spec:
  ports:
  - name: http
    port: 1026
    protocol: TCP
    targetPort: 1026
  selector:
    app: orion

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orion
  name: orion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orion
  template:
    metadata:
      labels:
        app: orion
    spec:
      containers:
      - command: ["orionld"]
        args: ["-fg", "-multiservice", "-ngsiv1Autocast", "-dbhost", "mongodb",
               "-logLevel", "DEBUG"]
        image: "fiware/orion-ld:1.0.1"
        imagePullPolicy: IfNotPresent
        name: orion
        ports:
        - containerPort: 1026
          name: http
        env:
        - name: ORIONLD_MONGO_HOST
          value: mongodb
        - name: ORIONLD_LOG_LEVEL
          value: DEBUG
        - name: ORIONLD_TRACE
          value: "true"
