apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/grafana
