apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
spec:
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
