apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-builtin-admin
  namespace: default
spec:
  encryptedData:
    password: AgAvCryTfd22ZvYwxZI9bINVN3TFxYw0SaC+SG+WCKX5+aoI4d/ZR75kCp1PiqfHOx0uCJMBxBPWHddMocOafzPOuc7wSJGit40RNmrdkayGlUdgR+HKy8GcS1VUGXZYoFUn0msxBvE/60jVwEPi6iXzaFrrlBm99ObFp7YY3ewx80D5TAgQoGT6dYeF2cCUBViZS05niQrqrgvH5l4I7kA9+Xkx8ddKUro4gvvlofFzhsK1SpCofSBOPnPG683fmHjSrPWNUAI767VTPrBNVMYquxdqD6jdhNH7x2IUHFeipJdusD6p15Rve0fXog4u8yFMAy/lXKm4ABrWVNIwFXVLpu+YFaen0qSIY5ginrawPoACitjxTdUnd/sn623ZJRIQGVz5sO+pqCKwQCkxmVLnT7iRDyPTvVZud6rGj5mlzS7d2NT+LPdz3STb2AVZm0Tn0XR4DVVIpVyXzKpXIIn1j+s4KKDj83ORyCX8b8xse53JYqVLqnjojvINeBsA9sF0YNvdceUeK9g5SvCRId3+2bcIDb3J4zUsx9Lwp3bLG0X1WsA9Zty+5ZsQyMntFdTyhgoIbuP3WSZjvv0xzhUwLGZunScPn0lQwX7Gl+EerrRuFjElP/rwtx6vellBd04zt0Czazn2fWW/ncOueW6u2DsEIFjki8ohC90NOzD13JVYcHkE6ZlhQuQqpBQkfA4VPaC68A+rTAtP2HkmU4pXKr/4bakfVW3ekYApyWR7NA==
    username: AgC18Ulaqiy+WQou8tpRTnxR2q6+6LGZZ8CQVbgoosKuv+g7NkHtxINswZ+NJG/2xYIjDX38vkzCsVFoPbv6kjHwOPm3jN7jjhLJf9QgO9yPghK6RJXtEKU8QmR5iRyTtfG0wINDjU/5wTSVlE+KmBvkRFlb2K+ksELhV/gg0tH/QWdyHPgm5ntMdeDB34TPTMToEZ9pA9oFszronmVSt9S4uuKgWUsGFVcNZekZ7bZaDcbttZHoCzF2tbc7N4N/7SucBjjo/UFPZqg4IXFht34M9OxGo01GlQ/xPWSErVO8nuYLqPs+HoXEtxq7n0Thtgl593h+0OfcC3i6yKIccLyVl6r/ugmcAslpAbWBbTaIw2y7eXtpJz/y8VvMjzfbRkOvQKcLOT+aqIA6wDhB6tFWYT+OK7AjHttPKPPrNGynNp/kv4Mgp20IWb61ti7I6oV/9UBRJrnom4dlHo6wehT4Rlf/iE5b+uiXiwIwGbbaZUYXj60+H9sqSt3mBWxR/4Aky6/G3Es5ZHhDegVDT9hHmH9MtEFRHX6CTey1C7dg5yjpMtdc6gV2StD87S09HcQh+Btl3rQWnphQjpAVVV1wexK/2NGgnfidgktd+UXaEsOMbpX+Xjbvte3rUbJldqcpeCcb0/t+eD9YKmQ4MXfeSPYHFhXFHNwZPq4FcCqSt0Rf5ZbGE1Ff3QTZBdLCGrM0fc7F7g==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: keycloak-builtin-admin
      namespace: default
    type: Opaque

