apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mosquitto-passwd
  namespace: default
spec:
  encryptedData:
    passwd: AgCvpcuZ5JKefbK/xNeg6xAgoOOj2gEXiKDPmBsCZ5pTDUC4jfggyS4qloohJEaZkgV/yfd5TGNk5sIKqiex5Bajj95SOJiroke1+LkX4eDozw6BkkvgBMdsJHaU0vUHQ35Q6Ivw+x4PqRf8VGVZl/JH7+zr7jBn4HZnA3Zrr1BRswrRYYFLqw1GrhoFLa/TLEYXDql8x0R2C40vSFbp9YTF6oxyhvG90i7JgWXbGD6F5Ed4Fau4GS7TaMViRWg6mhMWWB4T9Jgrbg0u9UNjuGkDpM5EfsEmBPRAfClsYcoPrJMNLw9lzEA9hnRbtWt1Jhvzt5RRVUUwZp4d/IgpY8U+5gLMlo7hXxmiGba/Gf7efD2Io2pKAbZJoQATmkS7CDUfPZL1Hlu7XoeA/qqOcieL+p72v0ZaeHgzGpSqXpPqkbkVDIifDImIEhDhZlBhNZrUnunCVdEbwOQGf/fmvnrmpn5lt1sNMmT5wY7ReMPlgQI1pKFh7C6M92vftigDvV4VNG3+NR6PmGJKMQf3EL5oja21pT73WAHOu9KgwCXz8TKG152H1TI75iVruv4xwtMj1Oc/qGsf3N4ua9ZosOECvaUBPgi17lFwzDhrPAB6a9Adh9SZ81SaEXJw/6D79jYyVI8QRtrBnHmJusxe2ca98+jq7kvm0vf+/omagyCXELBh4ZNEy1xfqVZSCjj760YWw5tfDYZE8BBRXBaax8GTq3FuEPo0+V0CI1S/M1LkWw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: mosquitto-passwd
      namespace: default
    type: Opaque

